---
# tasks file for vsftpd
- name: Install vsftpd
  package:
    name: vsftpd
    state: present

- name: Install some dependencies for SELinux
  package:
    name: policycoreutils-python-utils
    state: present

- name: Create dir {{item.path}}
  file:
    path: "{{ item.path }}"
    state: directory
    owner: ftp
    mode: "{{ item.mode }}"
  with_items:
    - path: "{{vsftpd_anon_root}}"
      mode: "0555"
    - path: "{{vsftpd_anon_root}}/upload"
      mode: "0777"

- name: Open firewall ports
  firewalld:
    port: 20-21/tcp
    state: enabled
    permanent: yes

- name: Start vsftpd
  service:
    name: vsftpd
    enabled: yes
    state: started

- name: Copy config
  template:
    dest: "{{ vsftpd_config_path }}"
    src: vsftpd.conf.j2
  notify: reload_vsftpd

- name: Change SElinux context for  "{{vsftpd_anon_root}}/upload"
  sefcontext:
    target: "{{vsftpd_anon_root}}/upload"
    setype: "public_content_rw_t"
    reload: True
    state: present

- name: Change SELinux boolean ftpd_anon_write
  seboolean:
    name: ftpd_anon_write
    state: yes
    persistent: yes
